# Generated by Django 5.2.8 on 2026-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_legalpage_options_legalpage_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalpage',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='legalpage',
            name='content_en',
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='content_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='content_en',
            field=models.TextField(blank=True),
        ),
    ]
