# Generated by Django 5.2.8 on 2026-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_remove_legalpage_content_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsection',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
