# Generated by Django 5.2.8 on 2025-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('content_ar', models.TextField()),
                ('content_en', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['slug'],
            },
        ),
    ]
