# Generated by Django 5.2.8 on 2026-03-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalpage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='legalpage',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_ar', models.TextField()),
                ('content_en', models.TextField()),
                ('anchor', models.SlugField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal.legalpage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'anchor')},
            },
        ),
    ]
