# Generated by Django 5.2.8 on 2026-04-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_alter_legalsection_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalsection',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='legalsection',
            name='content_en',
        ),
        migrations.CreateModel(
            name='LegalSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_ar', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='legal.legalsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
