# Generated by Django 5.2.8 on 2026-03-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_service_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceadvisoryrequest',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceadvisoryrequest',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='service_advisory/voice/'),
        ),
        migrations.CreateModel(
            name='ServiceAdvisoryRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.serviceadvisoryrequest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
