# Generated by Django 5.2.8 on 2026-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_appointmentsettings_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
