# Generated by Django 5.2.8 on 2026-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_appointmentslot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=10),
            preserve_default=False,
        ),
    ]
