# Generated by Django 5.2.8 on 2026-03-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_appointmentslot_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.appointmentslot'),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
