# Generated by Django 5.2.8 on 2026-05-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_formtemplate_context_type_and_more'),
        ('services', '0021_servicepagecms_alter_practicearea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepagecms',
            name='primary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepagecms',
            name='primary_button_label_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicepagecms',
            name='primary_button_label_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicepagecms',
            name='primary_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_page_buttons', to='form_builder.formtemplate'),
        ),
        migrations.AddField(
            model_name='servicepagecms',
            name='primary_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
