# Generated by Django 5.2.8 on 2026-05-20 18:12

import django.db.models.deletion
import apps.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_appointmentbooking_form_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBookingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appointments/files/all/', validators=[apps.services.validators.validate_file])),
                ('file_type', models.CharField(choices=[('attachment', 'Attachment'), ('voice_note', 'Voice Note')], max_length=30)),
                ('original_field_key', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.appointmentbooking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CareerApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='careers/files/', validators=[apps.services.validators.validate_file])),
                ('file_type', models.CharField(choices=[('cv_file', 'CV'), ('cover_letter', 'Cover Letter'), ('attachment', 'Attachment')], max_length=30)),
                ('original_field_key', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.careerapplication')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvisoryRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_advisory/files/', validators=[apps.services.validators.validate_file])),
                ('file_type', models.CharField(choices=[('attachment', 'Attachment'), ('voice_note', 'Voice Note')], max_length=30)),
                ('original_field_key', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.serviceadvisoryrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
