# Generated by Django 5.2.8 on 2026-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_appointmentbookingfile_careerapplicationfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='slot_date_snapshot',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='slot_end_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='slot_label_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='slot_shift_snapshot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='slot_start_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
