# Generated by Django 5.2.8 on 2026-05-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_appointmentbooking_slot_date_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsettings',
            old_name='price_in_person',
            new_name='default_price',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='title',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='visitors',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='voice_note',
        ),
    ]
