# Generated by Django 5.2.8 on 2026-05-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_rename_price_in_person_appointmentsettings_default_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='first_name_ar',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='last_name_ar',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='location',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='source',
        ),
        migrations.RemoveField(
            model_name='serviceadvisoryrequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='serviceadvisoryrequest',
            name='voice_note',
        ),
        migrations.DeleteModel(
            name='CareerApplicationFile',
        ),
    ]
