# Generated by Django 5.2.8 on 2026-05-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_remove_careerapplication_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestaccessactivity',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='services.servicerequestaccesslink'),
        ),
    ]
