# Generated by Django 5.2.8 on 2026-04-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_ar', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('logo_en', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('vat_logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('newsletter_title_ar', models.CharField(blank=True, max_length=255)),
                ('newsletter_title_en', models.CharField(blank=True, max_length=255)),
                ('copyright_ar', models.CharField(blank=True, max_length=255)),
                ('copyright_en', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('description_ar', models.CharField(blank=True, max_length=255)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
