# Generated by Django 5.2.8 on 2026-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_remove_aboutpage_subtitle_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
