# Generated by Django 5.2.8 on 2026-05-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_aboutpage_mobile_logo'),
        ('form_builder', '0002_formsection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcard',
            old_name='button_label_ar',
            new_name='primary_button_label_ar',
        ),
        migrations.RenameField(
            model_name='contactcard',
            old_name='button_label_en',
            new_name='primary_button_label_en',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='description2_ar',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='description2_en',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='url',
        ),
        migrations.AddField(
            model_name='contactcard',
            name='primary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='primary_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_primary_cards', to='form_builder.formtemplate'),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='primary_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='secondary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='secondary_button_label_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='secondary_button_label_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='secondary_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_secondary_cards', to='form_builder.formtemplate'),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='secondary_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('faq_preview', 'FAQ Preview')], default='default', max_length=20),
        ),
    ]
