# Generated by Django 5.2.8 on 2026-05-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_rename_button_label_ar_contactcard_primary_button_label_ar_and_more'),
        ('form_builder', '0003_infomodal_successresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='primary_info_modal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_cards', to='form_builder.infomodal'),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='secondary_info_modal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_contact_cards', to='form_builder.infomodal'),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='primary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal'), ('info_modal', 'Info Modal')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='secondary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal'), ('info_modal', 'Info Modal')], default='none', max_length=20),
        ),
    ]
