# Generated by Django 5.2.8 on 2026-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_contactcard_primary_info_modal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='primary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal'), ('info_modal', 'Info Modal'), ('contact_request', 'Contact Request')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='secondary_action_type',
            field=models.CharField(choices=[('none', 'None'), ('url', 'URL'), ('form_modal', 'Form Modal'), ('info_modal', 'Info Modal'), ('contact_request', 'Contact Request')], default='none', max_length=20),
        ),
    ]
