# Generated by Django 5.2.8 on 2025-12-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('job_title_ar', models.CharField(max_length=200)),
                ('job_title_en', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('lawyer', 'Lawyer'), ('partner', 'Partner'), ('consultant', 'Consultant'), ('advisor', 'Advisor'), ('manager', 'Manager'), ('other', 'Other')], default='lawyer', max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio_ar', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('experience_ar', models.TextField(blank=True)),
                ('experience_en', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name_ar'],
            },
        ),
    ]
