# Generated by Django 5.2.8 on 2026-02-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teamcategory_teampage_teammember_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio_ar',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='job_title_ar',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='job_title_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
    ]
