# Generated by Django 5.2.8 on 2026-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammember_options_teampage_left_link_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='categories',
        ),
        migrations.AddField(
            model_name='teammember',
            name='field_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='field_en',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
