# Generated by Django 5.2.8 on 2026-02-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_teammember_categories_teammember_field_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='sector_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='sector_en',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
