# Generated by Django 5.2.8 on 2025-12-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_practice_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdvisoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_top_ar', models.CharField(blank=True, max_length=255)),
                ('title_top_en', models.CharField(blank=True, max_length=255)),
                ('description_top_ar', models.TextField(blank=True)),
                ('description_top_en', models.TextField(blank=True)),
                ('title_bottom_ar', models.CharField(blank=True, max_length=255)),
                ('title_bottom_en', models.CharField(blank=True, max_length=255)),
                ('description_bottom_ar', models.TextField(blank=True)),
                ('description_bottom_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAdvisoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='service_advisory/')),
                ('status', models.CharField(default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
