# Generated by Django 5.2.8 on 2026-01-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceadvisorypage_serviceadvisoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_priced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
