# Generated by Django 5.2.8 on 2026-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_appointmentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsettings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentsettings',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='بالدقائق'),
        ),
    ]
