# Generated by Django 5.2.8 on 2026-02-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_careerjob_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='first_name_ar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='id_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='last_name_ar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
