# Generated by Django 5.2.8 on 2026-02-21 19:54

import django.db.models.deletion
from django.db import migrations, models

def fill_null_practice_area(apps, schema_editor):
    PracticeArea = apps.get_model("services", "PracticeArea")
    Service = apps.get_model("services", "Service")

    default_area, _ = PracticeArea.objects.get_or_create(
        slug="general",
        defaults={
            "name_ar": "عام",
            "name_en": "General",
            "is_active": True,
            "show_on_home": False,
            "order": 0,
        },
    )

    Service.objects.filter(practice_area__isnull=True).update(practice_area=default_area)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_pagecontent'),
        ('services', '0010_careerapplication_certifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_priced',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='services', to='cms.faqitem'),
        ),
        migrations.AddField(
            model_name='service',
            name='how_it_works_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='how_it_works_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_most_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='scope_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='scope_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='who_for_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='who_for_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),

        migrations.RunPython(fill_null_practice_area, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='service',
            name='practice_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.practicearea'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=300),
        ),
    ]
