# Generated by Django 5.2.8 on 2026-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_options_remove_service_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
