# Generated by Django 5.2.8 on 2026-02-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicearea',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
