# Generated by Django 5.2.8 on 2026-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_practicearea_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/items/'),
        ),
    ]
