# Generated by Django 5.2.8 on 2026-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_serviceadvisoryrequest_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsettings',
            name='price',
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='appointment_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='appointments/files/'),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='visitors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='appointments/voice/'),
        ),
        migrations.AddField(
            model_name='appointmentsettings',
            name='price_in_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsettings',
            name='price_online',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointmentbooking',
            constraint=models.UniqueConstraint(fields=('slot',), name='unique_slot_booking'),
        ),
    ]
