# Generated by Django 5.2.8 on 2026-05-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_appointmentbooking_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='deliverables_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='deliverables_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='how_it_works_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='how_it_works_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='overview_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='overview_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='practice_area',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scope_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scope_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='who_for_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='who_for_en',
        ),
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('serial_prefix', models.CharField(max_length=30, unique=True)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_services', to='services.practicearea')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='main_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.mainservice'),
        ),
        migrations.CreateModel(
            name='ServiceContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('overview', 'Overview'), ('who_for', 'Who For'), ('scope', 'Scope'), ('deliverables', 'Deliverables'), ('how_it_works', 'How It Works')], max_length=50)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('body_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
