# Generated by Django 5.2.8 on 2026-05-12 07:40

import django.db.models.deletion
import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_service_deliverables_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_logo', models.ImageField(blank=True, null=True, upload_to='services/page/logo/')),
                ('hero_media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/page/hero/')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='services/page/video/')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('search_placeholder_ar', models.CharField(blank=True, max_length=255)),
                ('search_placeholder_en', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='practicearea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description_ar',
            new_name='short_description_ar',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description_en',
            new_name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='serial_prefix',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='order',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='show_on_home',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_most_requested',
        ),
        migrations.AddField(
            model_name='mainservice',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/main/icons/'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='appointments/files/', validators=[services.validators.validate_file]),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='practice_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_services', to='services.practicearea'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='title_ar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/practice/icons/'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceadvisoryrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_advisory/', validators=[services.validators.validate_file]),
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('content_ar', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceContentSection',
        ),
    ]
