# Generated by Django 5.2.8 on 2026-05-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0014_formsubmissioneditlog_edited_by_admin'),
        ('services', '0023_serviceadvisoryrequest_form_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='form_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_booking', to='form_builder.formsubmission'),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='form_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_application', to='form_builder.formsubmission'),
        ),
        migrations.AddField(
            model_name='servicerequestaccesslink',
            name='editable_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
