# Generated by Django 5.2.8 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('news', 'News'), ('article', 'Article')], default='news', max_length=20),
        ),
    ]
