# Generated by Django 5.2.8 on 2026-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_ar', models.CharField(max_length=300)),
                ('page_title_en', models.CharField(max_length=300)),
                ('last_update_title_ar', models.CharField(max_length=300)),
                ('last_update_title_en', models.CharField(max_length=300)),
                ('last_update_description_ar', models.TextField(blank=True)),
                ('last_update_description_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
