# Generated by Django 5.2.8 on 2026-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogclause_content_ar_blogclause_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#353C3C', help_text='Hex color like #FF5733', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='blog/category_icons/'),
        ),
    ]
