# Generated by Django 5.2.8 on 2026-02-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
