# Generated by Django 5.2.8 on 2026-02-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogrelatedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogclause',
            name='content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogclause',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogclause',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogclause',
            name='title_ar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogclause',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
    ]
