# Generated by Django 5.2.8 on 2025-12-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_ar', models.CharField(default='شهم للمحاماة', max_length=200)),
                ('site_name_en', models.CharField(default='Shahm Law Firm', max_length=200)),
                ('contact_receiver_email', models.EmailField(default='', max_length=254)),
                ('auto_reply_email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100)),
                ('locale', models.CharField(default='ar', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
