# Generated by Django 5.2.8 on 2025-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('auto_reply', 'Auto Reply to Client'), ('subscription_welcome', 'Subscription Welcome Email'), ('admin_alert', 'Admin New Message Alert')], max_length=50, unique=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('html_content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='customer_reply_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='auto_reply_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_receiver_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
