# Generated by Django 5.2.8 on 2025-12-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_sitesettings_email_send_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_send_method',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gmail_access_token',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gmail_client_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gmail_client_secret',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gmail_redirect_uri',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gmail_refresh_token',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gmail_token_expiry',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_access_token',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_client_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_client_secret',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_redirect_uri',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_refresh_token',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_tenant_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='outlook_token_expiry',
        ),
    ]
