# Generated by Django 5.2.8 on 2025-12-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_broadcastlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastlog',
            options={'ordering': ['-created_at']},
        ),
    ]
