# Generated by Django 5.2.8 on 2025-12-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_broadcastlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('admin_alert', 'Admin Alert'), ('auto_reply', 'Auto Reply'), ('subscription_welcome', 'Subscription Welcome')], max_length=50, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('html_content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
