# Generated by Django 5.2.8 on 2026-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
