# Generated by Django 5.2.8 on 2026-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='team/hero/')),
                ('hero_description_ar', models.TextField(blank=True)),
                ('hero_description_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('bottom_image', models.ImageField(blank=True, null=True, upload_to='team/bottom/')),
                ('left_link_text_ar', models.CharField(blank=True, max_length=200)),
                ('left_link_text_en', models.CharField(blank=True, max_length=200)),
                ('left_link_url', models.CharField(blank=True, max_length=500)),
                ('right_link_text_ar', models.CharField(blank=True, max_length=200)),
                ('right_link_text_en', models.CharField(blank=True, max_length=200)),
                ('right_link_url', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='members', to='team.teamcategory'),
        ),
    ]
