# Generated by Django 5.2.8 on 2026-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_teammember_bio_ar_remove_teammember_bio_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name_ar']},
        ),
        migrations.AddField(
            model_name='teampage',
            name='left_link_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='right_link_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='team/members/'),
        ),
    ]
