# Generated by Django 5.2.8 on 2026-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_teammember_sector_ar_teammember_sector_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='cta_title_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='cta_title_en',
            field=models.TextField(blank=True),
        ),
    ]
