# Generated by Django 5.2.8 on 2026-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_teampage_cta_title_ar_teampage_cta_title_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teampage',
            old_name='cta_title_ar',
            new_name='left_cta_title_ar',
        ),
        migrations.RenameField(
            model_name='teampage',
            old_name='cta_title_en',
            new_name='left_cta_title_en',
        ),
        migrations.AddField(
            model_name='teampage',
            name='right_cta_title_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='right_cta_title_en',
            field=models.TextField(blank=True),
        ),
    ]
