# Generated by Django 5.2.8 on 2026-05-10 10:59

import django.db.models.deletion
import apps.form_builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_formsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SuccessResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='forms/success/')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('show_reference_number', models.BooleanField(default=False)),
                ('reference_prefix', models.CharField(blank=True, default='#', max_length=50)),
                ('button_label_ar', models.CharField(blank=True, max_length=100)),
                ('button_label_en', models.CharField(blank=True, max_length=100)),
                ('button_action_type', models.CharField(choices=[('none', 'None'), ('close', 'Close'), ('url', 'URL')], default='close', max_length=20)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='success_message_ar',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='success_message_en',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='public_reference',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='formsubmissionvalue',
            name='value_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.form_builder.models.submission_upload_path),
        ),
        migrations.CreateModel(
            name='InfoModalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('body_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form_builder.infomodal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='success_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='form_builder.successresponse'),
        ),
    ]
