# Generated by Django 5.2.8 on 2026-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_infomodal_successresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='context_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('appointments', 'Appointments'), ('services', 'Services'), ('careers', 'Careers')], default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='integration_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
