# Generated by Django 5.2.8 on 2026-05-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_formtemplate_context_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmissionEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='allow_public_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='allow_admin_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='allow_public_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='email_field_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='formsubmissionvalue',
            index=models.Index(fields=['submission'], name='form_builde_submiss_8dfc90_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmissionvalue',
            index=models.Index(fields=['submission', 'field'], name='form_builde_submiss_daaa63_idx'),
        ),
    ]
