# Generated by Django 5.2.8 on 2026-05-13 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_formsubmissioneditlog_formfield_allow_public_edit_and_more'),
        ('services', '0023_serviceadvisoryrequest_form_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmissioneditlog',
            name='edited_by_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicerequestaccesslink'),
        ),
        migrations.AddField(
            model_name='formsubmissioneditlog',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='form_builder.formsubmission'),
        ),
    ]
