# Generated by Django 5.2.8 on 2026-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_formsubmissioneditlog_edited_by_link_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('section', 'key')},
        ),
        migrations.AddField(
            model_name='formfield',
            name='system_key',
            field=models.CharField(blank=True, choices=[('title', 'Title'), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('first_name_ar', 'First Name Arabic'), ('last_name_ar', 'Last Name Arabic'), ('email', 'Email'), ('phone', 'Phone'), ('message', 'Message'), ('service_ids', 'Service IDs'), ('job_id', 'Job ID'), ('slot_id', 'Slot ID'), ('appointment_type', 'Appointment Type'), ('visitors', 'Visitors'), ('attachment', 'Attachment'), ('voice_note', 'Voice Note'), ('cv_file', 'CV File'), ('cover_letter', 'Cover Letter'), ('nationality', 'Nationality'), ('gender', 'Gender'), ('location', 'Location'), ('source', 'Source'), ('id_number', 'ID Number'), ('certifications', 'Certifications'), ('linkedin', 'LinkedIn'), ('notes', 'Notes')], db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('section', 'key'), ('section', 'system_key')},
        ),
    ]
