# Generated by Django 5.2.8 on 2026-05-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0008_formtemplate_requires_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='dynamic_source',
            field=models.CharField(blank=True, choices=[('services', 'Services'), ('career_jobs', 'Career Jobs'), ('appointment_slots', 'Appointment Slots')], max_length=100),
        ),
        migrations.AddField(
            model_name='formfield',
            name='option_source',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=20),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['option_source'], name='form_builde_option__343343_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['dynamic_source'], name='form_builde_dynamic_cf9377_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['system_key'], name='form_builde_system__f3850b_idx'),
        ),
    ]
