# Generated by Django 5.2.8 on 2026-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0010_alter_formfield_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(max_length=100),
        ),
    ]
