# Generated by Django 5.2.8 on 2026-05-19 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0013_alter_formfield_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmissioneditlog',
            name='edited_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_edit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
