# Generated by Django 5.2.8 on 2026-05-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0014_formsubmissioneditlog_edited_by_admin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formfield',
            name='unique_system_key_per_section',
        ),
    ]
