# Generated by Django 5.2.8 on 2026-05-21 11:36

import django.db.models.deletion
import apps.form_builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0015_remove_formfield_unique_system_key_per_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.form_builder.models.submission_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='form_builder.formsubmissionvalue')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
