# Generated by Django 5.2.8 on 2026-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0017_infomodalsection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='public_edit_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='public_edit_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['allow_public_edit'], name='form_builde_allow_p_bfa7ef_idx'),
        ),
    ]
