# Generated by Django 5.2.8 on 2026-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0021_alter_formfield_system_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='dynamic_source',
            field=models.CharField(blank=True, choices=[('service_categories', 'Service Categories'), ('services', 'Services'), ('career_jobs', 'Career Jobs'), ('appointment_slots', 'Appointment Slots')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='system_key',
            field=models.CharField(blank=True, choices=[('title', 'Title'), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('first_name_ar', 'First Name Arabic'), ('last_name_ar', 'Last Name Arabic'), ('email', 'Email'), ('phone', 'Phone'), ('message', 'Message'), ('service_category_id', 'Service Category ID'), ('service_ids', 'Service IDs'), ('job_id', 'Job ID'), ('slot_id', 'Slot ID'), ('appointment_date', 'Appointment Date'), ('appointment_type', 'Appointment Type'), ('visitors', 'Visitors'), ('attachment', 'Attachment'), ('voice_note', 'Voice Note'), ('cv_file', 'CV File'), ('cover_letter', 'Cover Letter'), ('nationality', 'Nationality'), ('gender', 'Gender'), ('location', 'Location'), ('source', 'Source'), ('id_number', 'ID Number'), ('certifications', 'Certifications'), ('linkedin', 'LinkedIn'), ('notes', 'Notes')], db_index=True, max_length=100),
        ),
    ]
