# Generated by Django 5.2.8 on 2026-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0024_alter_formfield_system_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='dynamic_source',
            field=models.CharField(blank=True, choices=[('service_categories', 'Service Categories'), ('services', 'Services'), ('career_jobs', 'Career Jobs'), ('appointment_slots', 'Appointment Slots'), ('appointment_periods', 'Appointment Periods')], max_length=100),
        ),
    ]
