# Generated by Django 5.2.8 on 2025-12-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('hover_text_ar', models.CharField(blank=True, max_length=200)),
                ('hover_text_en', models.CharField(blank=True, max_length=200)),
                ('left_title_ar', models.CharField(blank=True, max_length=200)),
                ('left_title_en', models.CharField(blank=True, max_length=200)),
                ('left_button_text_ar', models.CharField(blank=True, max_length=200)),
                ('left_button_text_en', models.CharField(blank=True, max_length=200)),
                ('left_button_url', models.CharField(blank=True, max_length=300)),
                ('right_title_ar', models.CharField(blank=True, max_length=200)),
                ('right_title_en', models.CharField(blank=True, max_length=200)),
                ('right_button_text_ar', models.CharField(blank=True, max_length=200)),
                ('right_button_text_en', models.CharField(blank=True, max_length=200)),
                ('right_button_url', models.CharField(blank=True, max_length=300)),
                ('center_button_text_ar', models.CharField(blank=True, max_length=200)),
                ('center_button_text_en', models.CharField(blank=True, max_length=200)),
                ('center_button_url', models.CharField(blank=True, max_length=300)),
                ('show_header', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('body_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/sections/')),
                ('button_text_ar', models.CharField(blank=True, max_length=100)),
                ('button_text_en', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('content_ar', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('page_status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon')], default='active', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('logo_desktop', 'Logo Desktop'), ('logo_mobile', 'Logo Mobile'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='hero/media/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.herosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='herosection',
            name='center_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_center_buttons', to='cms.page'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='left_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_left_buttons', to='cms.page'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='right_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_right_buttons', to='cms.page'),
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('link', 'Link'), ('logo', 'Logo')], default='link', max_length=10)),
                ('label_ar', models.CharField(blank=True, max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.headerlink')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ar', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('media_type', models.CharField(choices=[('link', 'Link'), ('footer_logo', 'Footer Logo')], default='link', max_length=20)),
                ('file', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.footercolumn')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.footerlink')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
