# Generated by Django 5.2.8 on 2025-12-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contactactionbutton_contactinfo_contactfaqpreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactactionbutton',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactfaqpreview',
            options={},
        ),
        migrations.RenameField(
            model_name='contactactionbutton',
            old_name='label_ar',
            new_name='button_label_ar',
        ),
        migrations.RenameField(
            model_name='contactactionbutton',
            old_name='label_en',
            new_name='button_label_en',
        ),
        migrations.AddField(
            model_name='contactactionbutton',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactactionbutton',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactactionbutton',
            name='title_ar',
            field=models.CharField(default='تواصل معنا', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactactionbutton',
            name='title_en',
            field=models.CharField(default='Contact Us', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactactionbutton',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
