# Generated by Django 5.2.8 on 2025-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_contactactionbutton_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Info'), ('button', 'Button'), ('form', 'Form'), ('faq', 'FAQ Preview')], max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description2_ar', models.TextField(blank=True)),
                ('description2_en', models.TextField(blank=True)),
                ('button_label_ar', models.CharField(blank=True, max_length=100)),
                ('button_label_en', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ContactActionButton',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
