# Generated by Django 5.2.8 on 2025-12-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_contactcard_delete_contactactionbutton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
