# Generated by Django 5.2.8 on 2026-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_contactpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('content_ar', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
