# Generated by Django 5.2.8 on 2026-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_footersettings_footercta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerlink',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='headerlink',
            name='description_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='headerlink',
            name='description_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='headerlink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='header/menu/'),
        ),
        migrations.AddField(
            model_name='headerlink',
            name='logo_variant',
            field=models.CharField(blank=True, choices=[('full_ar', 'Full Arabic'), ('scroll_ar', 'Scroll Arabic'), ('full_en', 'Full English'), ('scroll_en', 'Scroll English')], max_length=20),
        ),
        migrations.AddField(
            model_name='headerlink',
            name='slug',
            field=models.CharField(blank=True, help_text='/contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='headerlink',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('logo', 'Logo'), ('quick_access', 'Quick Access'), ('menu_image', 'Menu Image')], default='link', max_length=20),
        ),
    ]
