# Generated by Django 5.2.8 on 2026-05-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_faqcategory_faqitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cms.faqcategory'),
            preserve_default=False,
        ),
    ]
