# Generated by Django 5.2.8 on 2026-05-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_faqitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='about', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('media', models.FileField(blank=True, null=True, upload_to='about/')),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='about/partners/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('body_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='about/posts/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('body_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about/icons/')),
                ('label_ar', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='cms.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('label_ar', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cms.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
