# Generated by Django 5.2.8 on 2026-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_aboutpage_aboutpartner_aboutpost_aboutsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='partners_subtitle_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='partners_subtitle_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
