# Generated by Django 5.2.8 on 2026-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_aboutpage_partners_subtitle_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/posts/'),
        ),
    ]
