# Generated by Django 5.2.8 on 2026-05-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_aboutpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='title_en',
        ),
    ]
