# Generated by Django 5.2.8 on 2026-05-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_remove_aboutpage_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='subtitle_en',
        ),
    ]
