# Generated by Django 5.2.8 on 2026-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_contactcard_primary_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='left_button_slug',
            field=models.CharField(blank=True, help_text='/contact', max_length=300),
        ),
        migrations.AddField(
            model_name='herosection',
            name='right_button_slug',
            field=models.CharField(blank=True, help_text='/about', max_length=300),
        ),
    ]
