# Generated by Django 5.2.17 on 2026-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_herosection_left_button_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='subtitle_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='subtitle_en',
            field=models.TextField(blank=True),
        ),
    ]
