# Generated by Django 5.2.8 on 2026-05-09 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('submit_button_text_ar', models.CharField(default='إرسال', max_length=100)),
                ('submit_button_text_en', models.CharField(default='Submit', max_length=100)),
                ('success_message_ar', models.CharField(default='تم إرسال النموذج بنجاح', max_length=255)),
                ('success_message_en', models.CharField(default='Form submitted successfully', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_login', models.BooleanField(default=False)),
                ('allow_multiple_submissions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form_builder.formtemplate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file', 'File')], max_length=30)),
                ('key', models.SlugField(max_length=100)),
                ('label_ar', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('placeholder_ar', models.CharField(blank=True, max_length=255)),
                ('placeholder_en', models.CharField(blank=True, max_length=255)),
                ('help_text_ar', models.CharField(blank=True, max_length=255)),
                ('help_text_en', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.CharField(choices=[('full', 'Full'), ('half', 'Half'), ('third', 'Third')], default='full', max_length=20)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_builder.formtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ar', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('value', models.SlugField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form_builder.formfield')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='form-submissions/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_values', to='form_builder.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='form_builder.formsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['field'], name='form_builde_field_i_2c65fd_idx')],
                'unique_together': {('submission', 'field')},
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['slug'], name='form_builde_slug_d4291a_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['is_active'], name='form_builde_is_acti_9f3862_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'status'], name='form_builde_form_id_4ecbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['submitted_at'], name='form_builde_submitt_79ac3e_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form', 'order'], name='form_builde_form_id_d6e1da_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['field_type'], name='form_builde_field_t_147d77_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['is_active'], name='form_builde_is_acti_0b17a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'key')},
        ),
    ]
