# Generated by Django 5.2.8 on 2026-05-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='formfield',
            name='form_builde_form_id_d6e1da_idx',
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='require_terms_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='terms_text_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='terms_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formsection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form_builder.formtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_builder.formsection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('section', 'key')},
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['section', 'order'], name='form_builde_section_47059e_idx'),
        ),
        migrations.AddIndex(
            model_name='formsection',
            index=models.Index(fields=['form', 'order'], name='form_builde_form_id_a6f5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='formsection',
            index=models.Index(fields=['is_active'], name='form_builde_is_acti_217db5_idx'),
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='form',
        ),
    ]
