# Generated by Django 5.2.8 on 2026-05-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0007_alter_formfield_unique_together_formfield_system_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='requires_verification',
            field=models.BooleanField(default=False),
        ),
    ]
