# Generated by Django 5.2.8 on 2026-05-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0009_formfield_dynamic_source_formfield_option_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
