# Generated by Django 5.2.8 on 2026-05-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0011_alter_formfield_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('section', 'key')},
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key', ''), _negated=True), fields=('section', 'system_key'), name='unique_system_key_per_section'),
        ),
    ]
