# Generated by Django 5.2.8 on 2026-05-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0012_alter_formfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
