# Generated by Django 5.2.8 on 2026-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0016_formsubmissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodalsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
