# Generated by Django 5.2.8 on 2026-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0018_formsubmission_public_edit_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(choices=[('dynamic', 'Dynamic Form'), ('info', 'Info Form')], db_index=True, default='dynamic', max_length=20),
        ),
    ]
