# Generated by Django 5.2.8 on 2026-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0022_alter_formfield_dynamic_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successresponse',
            name='reference_prefix',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
