# Generated by Django 5.2.8 on 2025-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_emailtemplate_sitesettings_admin_notify_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_send_method',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('gmail_oauth', 'Gmail OAuth'), ('outlook_oauth', 'Outlook OAuth')], default='smtp', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_redirect_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gmail_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_redirect_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_tenant_id',
            field=models.CharField(blank=True, help_text='مثال: common أو organizations أو tenant ID', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outlook_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
