# Generated by Django 5.2.8 on 2026-05-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_sitesettings_tiktok_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
